#print('*'*50)
name = input("请输入姓名")
gender = input("请输入性别")
phone = input("请输入电话号码")
addr = input("请输入家庭住址")
email = input("请输入邮箱号码")
#print("姓名%s\n"%name,"性别%s\n"%gender,"电话：%s\n"%phone)
print('*'*50)
print("姓名%s\n性别%s\n电话%s\n家庭住址%s\n邮箱是%s\n"%(name,gender,phone,addr,email))
print('*'*50)
